/**
 * Build-time keyword index helper. The raw JSON is generated by
 * `scripts/generate-keyword-index.mjs` (run before `astro build` /
 * `astro dev` via the npm scripts) and is gitignored — always
 * present at build time but not tracked in source control.
 *
 * Why this module exists: each `.astro` consumer used to read the
 * file via `path.dirname(fileURLToPath(import.meta.url))` +
 * `readFileSync`. That worked in `astro dev` (where
 * `import.meta.url` is the source file URL) but silently failed in
 * `astro build` — the SSR bundle's `import.meta.url` points into
 * the chunk output, so the relative `..×N` path no longer reaches
 * `src/data/`. Result: `existsSync` returned false, the consumers
 * defaulted to empty data, and production lost both the keyword
 * pages and the entry-meta backlink counts.
 *
 * Switching to a JSON `import` lets Vite resolve the path
 * statically. Centralizing the cast and the `counts` derivation
 * here keeps the type definitions and the
 * `as unknown as KeywordIndex` cast in a single place instead of
 * duplicating them across three frontmatter blocks.
 *
 * `getStaticPaths` consumers can read from this module directly:
 * Astro's isolated `getStaticPaths` scope only sees file imports
 * (not the surrounding frontmatter `const`s), and `keywordIndex`
 * is exactly that — a file import.
 */
import keywordIndexRaw from '../data/keyword-index.json';

export interface KeywordIndexLocale {
  concept: Record<string, string>;
  person: Record<string, string>;
  counts: Record<string, number>;
  backlinks: Record<string, string[]>;
  slugs: Record<string, string>;
}

export interface KeywordIndex {
  en: KeywordIndexLocale;
  ja: KeywordIndexLocale;
}

export const keywordIndex = keywordIndexRaw as unknown as KeywordIndex;

/**
 * Locale → keyword → backlink count, flattened from `keywordIndex`.
 * Mirrors the shape EntryMeta uses to render the `(N)` suffix on
 * inline keyword links. Kept here (rather than only in EntryMeta)
 * so future consumers — search-result keyword chips, keyword
 * listing pages, etc. — can reuse the same flattening without
 * recomputing.
 */
export const keywordCounts: Record<string, Record<string, number>> = {
  en: keywordIndex.en?.counts ?? {},
  ja: keywordIndex.ja?.counts ?? {},
};
