/**
 * Build-time keyword index helper. The raw JSON is generated by
 * `scripts/generate-keyword-index.mjs` (run before `astro build` /
 * `astro dev` via the npm scripts) and is gitignored — always
 * present at build time but not tracked in source control.
 *
 * Why this module exists: each `.astro` consumer used to read the
 * file via `path.dirname(fileURLToPath(import.meta.url))` +
 * `readFileSync`. That worked in `astro dev` (where
 * `import.meta.url` is the source file URL) but silently failed in
 * `astro build` — the SSR bundle's `import.meta.url` points into
 * the chunk output, so the relative `..×N` path no longer reaches
 * `src/data/`. Result: `existsSync` returned false, the consumers
 * defaulted to empty data, and production lost both the keyword
 * pages and the entry-meta backlink counts.
 *
 * Switching to a JSON `import` lets Vite resolve the path
 * statically. Centralizing the cast and the `counts` derivation
 * here keeps the type definitions and the
 * `as unknown as KeywordIndex` cast in a single place instead of
 * duplicating them across three frontmatter blocks.
 *
 * `getStaticPaths` consumers can read from this module directly:
 * Astro's isolated `getStaticPaths` scope only sees file imports
 * (not the surrounding frontmatter `const`s), and `keywordIndex`
 * is exactly that — a file import.
 */
import keywordIndexRaw from '../data/keyword-index.json';

export interface KeywordIndexLocale {
  concept: Record<string, string>;
  person: Record<string, string>;
  counts: Record<string, number>;
  backlinks: Record<string, string[]>;
  slugs: Record<string, string>;
}

export interface KeywordIndex {
  en: KeywordIndexLocale;
  ja: KeywordIndexLocale;
}

export const keywordIndex = keywordIndexRaw as unknown as KeywordIndex;

/**
 * Locale → keyword → backlink count, flattened from `keywordIndex`.
 * Mirrors the shape EntryMeta uses to render the `(N)` suffix on
 * inline keyword links. Kept here (rather than only in EntryMeta)
 * so future consumers — search-result keyword chips, keyword
 * listing pages, etc. — can reuse the same flattening without
 * recomputing.
 */
export const keywordCounts: Record<string, Record<string, number>> = {
  en: keywordIndex.en?.counts ?? {},
  ja: keywordIndex.ja?.counts ?? {},
};

/**
 * Locale → keyword → URL slug, inverted from `keywordIndex.{locale}.slugs`
 * (which maps slug → keyword). Any consumer that needs a keyword's href
 * must read this map rather than re-deriving a slug from the keyword text
 * with `slugifyKeyword()` -- primary person keywords route through their
 * participant's own canonical slug (see generate-keyword-index.mjs pass 5),
 * not a re-slugified display name, so recomputing silently drifts (found
 * 2026-09-01: 48 of 51 JA person keywords produced a broken href this way,
 * e.g. "ウェイ・ダイ" re-slugified to "ウェイ-ダイ" instead of the real
 * "wei-dai"). This map is the single source of truth for that lookup.
 */
export const keywordSlugs: Record<string, Record<string, string>> = {
  en: Object.fromEntries(Object.entries(keywordIndex.en?.slugs ?? {}).map(([slug, kw]) => [kw, slug])),
  ja: Object.fromEntries(Object.entries(keywordIndex.ja?.slugs ?? {}).map(([slug, kw]) => [kw, slug])),
};

/**
 * A handful of JA concept keywords are the untranslated original title of
 * an external work quoted verbatim in JA body prose (e.g. an aftermath
 * article citing the LessWrong post "Bitcoins are not digital greenbacks"
 * by its own name) -- correct per STYLE_GUIDE_REFERENCE.md's Auto-Link
 * Keywords section, not a translation gap (confirmed 2026-09-01). Left
 * bare, a full English title reads as if the JA page itself switched
 * language; JA body prose already marks exactly this case with corner
 * brackets (『...』) when citing an external title, so reuse that same
 * convention wherever such a keyword stands alone as a label. No per-
 * keyword classification is needed -- ANY keyword with no Japanese
 * characters gets this treatment uniformly, whether it's a citation like
 * this or a short technical term (Hashcash, UTXO): 『』 also reads
 * naturally in Japanese as "this exact term/name is being called out."
 * Shared here (rather than duplicated per page) so JA keyword detail
 * pages, the JA keyword index, and EntryMeta's "Defines:" row agree.
 */
export const hasJapanese = (s: string): boolean => /[぀-ヿ㐀-鿿＀-￯]/.test(s);
/** Standalone label position (H1, <title>, nav sibling labels, EntryMeta's
    "Defines:" row) that currently shows the keyword bare with no
    punctuation of its own. */
export const keywordLabel = (kw: string): string => (hasJapanese(kw) ? kw : `『${kw}』`);
/** Position that already wraps the keyword in JA quotation marks inside a
    sentence ("「keyword」が言及...") -- swap to the same corner brackets for
    an ASCII-only keyword instead of stacking bracket styles. */
export const keywordQuoted = (kw: string): string => (hasJapanese(kw) ? `「${kw}」` : `『${kw}』`);
